import ***REMOVED*** CustomError ***REMOVED*** from './CustomError';
/**
 * These are the kind of errors that should never happen.
 *
 * If you see one thrown, please file a bug in the GitHub issue tracker.
 */
export declare class HellFreezesOverError extends CustomError ***REMOVED***
    constructor(message: string);
***REMOVED***
