import ***REMOVED*** CustomError ***REMOVED*** from './CustomError';
export declare class RetryAfterError extends CustomError ***REMOVED***
    private readonly _retryAt;
    constructor(after: number);
    get retryAt(): number;
***REMOVED***
